#!/usr/bin/env bash
# redirection
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
command="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "42i $command" /etc/nginx/sites-available/default
service nginx start
