#!/usr/bin/env bash
# not found page 404
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
command="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "42i $command" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
error="\\\terror_page 404 \/custom_404.html;\nlocation = \/custom_404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"
sed -i "44i $error" /etc/nginx/sites-available/default
service nginx start
