#!/usr/bin/env bash
# Install and configure HAproxy in server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "frontend Local_server
     	bind *:80
	mode http
	default_backend nodes

backend nodes
	balance roundrobin
	server 1537-web-01 35.237.45.130:80 check
	server 1537-web-02 35.196.139.55:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
