#!/usr/bin/env bash
# Install and configure HAproxy in server
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*
echo "frontend Local_server
     	bind *:80
	mode http
	default_backend nodes

backend nodes
	balance roundrobin
	server 1537-web-01 34.73.35.13:80 check
	server 1537-web-02 3.88.220.170:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
